In [1]:
import numpy as np

from utils_knn import get_acc_knn
from load_datasets import get_BBC

In [2]:
X, y, w, idx_train, idx_test, idx_docs, n_words = get_BBC()

str_dataset = "_BBC"
path = "./results"+str_dataset+"/"

str_d = "_d30"

### WMD

In [3]:
dist_mat = np.loadtxt(path + "d_wmd_w2_BBC_k0")

L_acc = get_acc_knn(dist_mat, y, idx_train, idx_test)
np.mean(L_acc)

0.9454545454545455

In [4]:
L_acc

[0.9454545454545454,
 0.9636363636363636,
 0.9545454545454546,
 0.9181818181818182,
 0.9454545454545454]

### WMD + SW

In [5]:
str_loss = "_sw"
str_projs = "_projs500"

In [6]:
L_sw = []

for k in range(3):
    d_sw = np.loadtxt(path + "d_wmd"+str_loss+str_dataset+str_projs+"_k"+str(k))
    L_acc = get_acc_knn(d_sw, y, idx_train, idx_test)
    L_sw.append(L_acc)

L_acc = np.array(L_sw)
means = np.mean(L_acc, axis=-1)
print(np.mean(means), np.std(means))

0.8942424242424242 0.008855538906789298


In [7]:
L_acc

array([[0.88636364, 0.89545455, 0.87272727, 0.87727273, 0.89545455],
       [0.90909091, 0.91818182, 0.90454545, 0.89090909, 0.90909091],
       [0.89545455, 0.91363636, 0.9       , 0.86363636, 0.88181818]])

In [8]:
means = np.mean(L_acc, axis=0)
means

array([0.8969697 , 0.90909091, 0.89242424, 0.87727273, 0.89545455])

### WCD + WMD

In [9]:
str_loss = "_w2"

In [10]:
L_acc = []

for i in range(len(idx_train)):
    dist_mat = np.loadtxt(path + "d_swmd_wcd"+str_d+str_loss+str_dataset+"_i"+str(i)+"_k0")
    L_acc += get_acc_knn(dist_mat, y, [idx_train[i]], [idx_test[i]])
    
print(np.mean(L_acc), np.std(L_acc))

0.9836363636363638 0.008430562268632459


In [11]:
L_acc

[0.990909090909091,
 0.9954545454545455,
 0.9772727272727273,
 0.9818181818181818,
 0.9727272727272728]

### WCD + WMD + SW

In [12]:
str_loss = "_sw"
str_projs = "_projs500"

In [13]:
L_acc = np.zeros((3, len(idx_train)))

for k in range(3):
    for i in range(len(idx_train)):
        dist_mat = np.loadtxt(path + "d_swmd_wcd"+str_d+str_loss+str_dataset+
                              str_projs+"_i"+str(i)+"_k"+str(k))
        L_acc[k, i] = get_acc_knn(dist_mat, y, [idx_train[i]], [idx_test[i]])[0]
    
means = np.mean(L_acc, axis=-1)
print(np.mean(means), np.std(means))

0.9757575757575757 0.0004285495643554599


In [14]:
L_acc

array([[0.97727273, 0.99090909, 0.96818182, 0.96818182, 0.97272727],
       [0.97272727, 0.99090909, 0.96818182, 0.97727273, 0.97272727],
       [0.97272727, 0.99090909, 0.96818182, 0.97727273, 0.96818182]])

In [15]:
means = np.mean(L_acc, axis=0)
means

array([0.97424242, 0.99090909, 0.96818182, 0.97424242, 0.97121212])