In [1]:
import numpy as np

from utils_knn import get_acc_knn
from load_datasets import get_movies

In [2]:
X, y, w, idx_train, idx_test, idx_docs, n_words = get_movies()

str_dataset = "_movie"
path = "./results"+str_dataset+"/"

str_d = "_d30"

### WMD

In [3]:
dist_mat = np.loadtxt(path + "d_wmd_w2_movie_k0")

L_acc = get_acc_knn(dist_mat, y, idx_train, idx_test)
np.mean(L_acc)

0.7444

In [4]:
L_acc

[0.732, 0.724, 0.756, 0.752, 0.758]

### WMD + SW

In [5]:
str_loss = "_sw"
str_projs = "_projs500"

In [6]:
L_sw = []

for k in range(3):
    d_sw = np.loadtxt(path + "d_wmd"+str_loss+str_dataset+str_projs+"_k"+str(k))
    L_acc = get_acc_knn(d_sw, y, idx_train, idx_test)
    L_sw.append(L_acc)

L_acc = np.array(L_sw)
means = np.mean(L_acc, axis=-1)
print(np.mean(means), np.std(means))

0.6726666666666667 0.006861162842809939


In [7]:
L_acc

array([[0.664, 0.71 , 0.67 , 0.682, 0.68 ],
       [0.662, 0.688, 0.656, 0.694, 0.662],
       [0.644, 0.67 , 0.67 , 0.664, 0.674]])

In [8]:
means = np.mean(L_acc, axis=0)
means

array([0.65666667, 0.68933333, 0.66533333, 0.68      , 0.672     ])

### WCD + WMD

In [9]:
str_loss = "_w2"

In [10]:
L_acc = []

for i in range(len(idx_train)):
    dist_mat = np.loadtxt(path + "d_swmd_wcd"+str_d+str_loss+str_dataset+"_i"+str(i)+"_k0")
    L_acc += get_acc_knn(dist_mat, y, [idx_train[i]], [idx_test[i]])
    
print(np.mean(L_acc), np.std(L_acc))

0.7604000000000001 0.023268863315598402


In [11]:
L_acc

[0.736, 0.772, 0.734, 0.764, 0.796]

### WCD + WMD + SW

In [12]:
str_loss = "_sw"
str_projs = "_projs500"

In [13]:
L_acc = np.zeros((3, len(idx_train)))

for k in range(3):
    for i in range(len(idx_train)):
        dist_mat = np.loadtxt(path + "d_swmd_wcd"+str_d+str_loss+str_dataset+
                              str_projs+"_i"+str(i)+"_k"+str(k))
        L_acc[k, i] = get_acc_knn(dist_mat, y, [idx_train[i]], [idx_test[i]])[0]
    
means = np.mean(L_acc, axis=-1)
print(np.mean(means), np.std(means))

0.7654666666666667 0.0011469767022724046


In [14]:
L_acc

array([[0.728, 0.784, 0.736, 0.778, 0.794],
       [0.73 , 0.782, 0.752, 0.774, 0.796],
       [0.728, 0.786, 0.736, 0.778, 0.8  ]])

In [15]:
means = np.mean(L_acc, axis=0)
means

array([0.72866667, 0.784     , 0.74133333, 0.77666667, 0.79666667])