In [1]:
import numpy as np

from utils_knn import get_acc_knn
from load_datasets import get_goodreads

# Like

In [2]:
X, y, w, idx_train, idx_test, idx_docs, n_words = get_goodreads(task="likability")

str_dataset = "_goodreads_like"
path = "./results"+str_dataset+"/"

str_d = "_d30"

### WMD

In [3]:
str_dataset = "_goodreads_genre"
path = "./results"+str_dataset+"/"

dist_mat = np.loadtxt(path + "d_wmd_w2_goodreads_genre_k0")

L_acc = get_acc_knn(dist_mat, y, idx_train, idx_test)
np.mean(L_acc)

0.7099601593625497

In [4]:
L_acc

[0.7370517928286853,
 0.7171314741035857,
 0.6972111553784861,
 0.7131474103585658,
 0.6852589641434262]

### WMD + SW

In [5]:
str_loss = "_sw"
str_projs = "_projs500"

str_dataset = "_goodreads_genre"
path = "./results"+str_dataset+"/"

In [6]:
L_sw = []

for k in range(3):
    d_sw = np.loadtxt(path + "d_wmd"+str_loss+str_dataset+str_projs+"_k"+str(k))
    L_acc = get_acc_knn(d_sw, y, idx_train, idx_test)
    L_sw.append(L_acc)

L_acc = np.array(L_sw)
means = np.mean(L_acc, axis=-1)
print(np.mean(means), np.std(means))

0.6589641434262948 0.0017213122704934506


In [7]:
L_acc

array([[0.64940239, 0.66932271, 0.66135458, 0.64143426, 0.66932271],
       [0.66932271, 0.6374502 , 0.66932271, 0.67729084, 0.65338645],
       [0.68924303, 0.64143426, 0.67729084, 0.66533865, 0.61354582]])

In [8]:
means = np.mean(L_acc, axis=0)
means

array([0.66932271, 0.64940239, 0.66932271, 0.66135458, 0.64541833])

### WCD + WMD

In [9]:
str_dataset = "_goodreads_like"
path = "./results"+str_dataset+"/"
str_loss = "_w2"

In [10]:
L_acc = []

for i in range(len(idx_train)):
    dist_mat = np.loadtxt(path + "d_swmd_wcd"+str_d+str_loss+str_dataset+"_i"+str(i)+"_k0")
    L_acc += get_acc_knn(dist_mat, y, [idx_train[i]], [idx_test[i]])
    
print(np.mean(L_acc), np.std(L_acc))

0.6836653386454182 0.024115929801468643


In [11]:
L_acc

[0.6733067729083665,
 0.7091633466135459,
 0.6972111553784861,
 0.6414342629482072,
 0.6972111553784861]

### WCD + WMD + SW

In [12]:
str_loss = "_sw"
str_projs = "_projs500"

In [13]:
L_acc = np.zeros((3, len(idx_train)))

for k in range(3):
    for i in range(len(idx_train)):
        dist_mat = np.loadtxt(path + "d_swmd_wcd"+str_d+str_loss+str_dataset+
                              str_projs+"_i"+str(i)+"_k"+str(k))
        L_acc[k, i] = get_acc_knn(dist_mat, y, [idx_train[i]], [idx_test[i]])[0]
    
means = np.mean(L_acc, axis=-1)
print(np.mean(means), np.std(means))

0.6754316069057106 0.001354321251950275


In [14]:
L_acc

array([[0.65338645, 0.71314741, 0.70119522, 0.66533865, 0.65338645],
       [0.65737052, 0.69322709, 0.68525896, 0.67729084, 0.66135458],
       [0.65737052, 0.70916335, 0.6812749 , 0.67330677, 0.64940239]])

In [15]:
means = np.mean(L_acc, axis=0)
means

array([0.6560425 , 0.70517928, 0.68924303, 0.67197875, 0.65471448])

# Genre

In [16]:
X, y, w, idx_train, idx_test, idx_docs, n_words = get_goodreads(task="genre")

str_dataset = "_goodreads_genre"
path = "./results"+str_dataset+"/"

str_d = "_d30"

### WMD

In [17]:
dist_mat = np.loadtxt(path + "d_wmd_w2_goodreads_genre_k0")

L_acc = get_acc_knn(dist_mat, y, idx_train, idx_test)
np.mean(L_acc)

0.5617529880478087

In [18]:
L_acc

[0.5099601593625498,
 0.5816733067729084,
 0.5537848605577689,
 0.5697211155378487,
 0.5936254980079682]

### WMD + SW

In [19]:
str_loss = "_sw"
str_projs = "_projs500"

In [20]:
L_sw = []

for k in range(3):
    d_sw = np.loadtxt(path + "d_wmd"+str_loss+str_dataset+str_projs+"_k"+str(k))
    L_acc = get_acc_knn(d_sw, y, idx_train, idx_test)
    L_sw.append(L_acc)

L_acc = np.array(L_sw)
means = np.mean(L_acc, axis=-1)
print(np.mean(means), np.std(means))

0.500132802124834 0.012090100054970536


In [21]:
L_acc

array([[0.46613546, 0.49800797, 0.47011952, 0.46215139, 0.52191235],
       [0.46215139, 0.49800797, 0.49003984, 0.52191235, 0.5498008 ],
       [0.49800797, 0.4940239 , 0.52191235, 0.50199203, 0.54581673]])

In [22]:
means = np.mean(L_acc, axis=0)
means

array([0.47543161, 0.49667995, 0.4940239 , 0.49535193, 0.53917663])

### WCD + WMD

In [23]:
str_loss = "_w2"

In [24]:
L_acc = []

for i in range(len(idx_train)):
    dist_mat = np.loadtxt(path + "d_swmd_wcd"+str_d+str_loss+str_dataset+"_i"+str(i)+"_k0")
    L_acc += get_acc_knn(dist_mat, y, [idx_train[i]], [idx_test[i]])
    
print(np.mean(L_acc), np.std(L_acc))

0.5681274900398405 0.01895677649939496


In [25]:
L_acc

[0.5577689243027888,
 0.545816733067729,
 0.5737051792828686,
 0.601593625498008,
 0.5617529880478087]

### WCD + WMD + SW

In [26]:
str_loss = "_sw"
str_projs = "_projs500"

In [27]:
L_acc = np.zeros((3, len(idx_train)))

for k in range(3):
    for i in range(len(idx_train)):
        dist_mat = np.loadtxt(path + "d_swmd_wcd"+str_d+str_loss+str_dataset+
                              str_projs+"_i"+str(i)+"_k"+str(k))
        L_acc[k, i] = get_acc_knn(dist_mat, y, [idx_train[i]], [idx_test[i]])[0]
    
means = np.mean(L_acc, axis=-1)
print(np.mean(means), np.std(means))

0.5702523240371845 0.006771606259751368


In [28]:
L_acc

array([[0.55378486, 0.54581673, 0.58964143, 0.57370518, 0.54183267],
       [0.57370518, 0.5498008 , 0.59760956, 0.57768924, 0.58565737],
       [0.58565737, 0.5498008 , 0.58565737, 0.57768924, 0.56573705]])

In [29]:
means = np.mean(L_acc, axis=0)
means

array([0.57104914, 0.54847278, 0.59096946, 0.57636122, 0.56440903])